apiVersion: v1
kind: PersistentVolume
metadata:
  name: mariadb1-pv-volume
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    server: KATACODA-DYNAMIC-IP
    path: /exports/data-0001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mariadb1-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi